################
### Settings ###
################

collection = "nightly-230515"

[idris2]
url     = "https://github.com/buzden/Idris2"
version = "0.6.0"
commit  = "ac0b0acc0289517140387bc7eeb277c6feb76dae"

[install]
whitelist = [ "deptycheck-tests", "pil-tests", "deptycheck-docs" ]

##############
### Locals ###
##############

[custom.all.deptycheck]
type = "local"
path = "."
ipkg = "deptycheck.ipkg"
test = "tests/tests.ipkg"

[custom.all.pil]
type = "local"
path = "examples/pil"
ipkg = "pil.ipkg"
test = "tests/tests.ipkg"

[custom.all.docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

####################
### Thirdparties ###
####################

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/buzden/idris2-elab-util"
commit = "d4094ced71570a6f10df4c2486ea90778da2f7e3"
ipkg   = "elab-util.ipkg"

[custom.all.sop]
type   = "git"
url    = "https://github.com/buzden/idris2-sop"
commit = "a9efb67d23adf3808bfd887781586ef318c56f35"
ipkg   = "sop.ipkg"
